In [1]:
#add dependencies
import requests
import json
import pandas as pd
from sodapy import Socrata

In [2]:
client = Socrata('data.cdc.gov', 
                  '2a6M2xadlitlChvZssCcGyMYI',
                  "roudyb3@gmail.com",
                  "D@taisfun2020")

In [7]:
results = client.get("unsk-b7fc", limit=21000)

In [23]:
results_df = pd.DataFrame.from_records(results)

In [10]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20255 entries, 0 to 20254
Data columns (total 69 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   date                             20255 non-null  object
 1   mmwr_week                        20255 non-null  object
 2   location                         20255 non-null  object
 3   distributed                      20255 non-null  object
 4   distributed_janssen              20255 non-null  object
 5   distributed_moderna              20255 non-null  object
 6   distributed_pfizer               20255 non-null  object
 7   distributed_unk_manuf            20255 non-null  object
 8   dist_per_100k                    20255 non-null  object
 9   distributed_per_100k_12plus      20255 non-null  object
 10  distributed_per_100k_18plus      20255 non-null  object
 11  distributed_per_100k_65plus      20255 non-null  object
 12  administered                     20255 non-null  object
 13  administered_12plus              20255 non-null  object
 14  administered_18plus              20255 non-null  object
 15  administered_65plus              20255 non-null  object
 16  administered_janssen             20255 non-null  object
 17  administered_moderna             20255 non-null  object
 18  administered_pfizer              20255 non-null  object
 19  administered_unk_manuf           20255 non-null  object
 20  admin_per_100k                   20255 non-null  object
 21  admin_per_100k_12plus            20255 non-null  object
 22  admin_per_100k_18plus            20255 non-null  object
 23  admin_per_100k_65plus            20255 non-null  object
 24  recip_administered               20255 non-null  object
 25  administered_dose1_recip         20255 non-null  object
 26  administered_dose1_pop_pct       20255 non-null  object
 27  administered_dose1_recip_1       20255 non-null  object
 28  administered_dose1_recip_2       20255 non-null  object
 29  administered_dose1_recip_3       20255 non-null  object
 30  administered_dose1_recip_4       20255 non-null  object
 31  administered_dose1_recip_5       20255 non-null  object
 32  administered_dose1_recip_6       20255 non-null  object
 33  series_complete_yes              20255 non-null  object
 34  series_complete_pop_pct          20255 non-null  object
 35  series_complete_12plus           20255 non-null  object
 36  series_complete_12pluspop        20255 non-null  object
 37  series_complete_18plus           20255 non-null  object
 38  series_complete_18pluspop        20255 non-null  object
 39  series_complete_65plus           20255 non-null  object
 40  series_complete_65pluspop        20255 non-null  object
 41  series_complete_janssen          20255 non-null  object
 42  series_complete_moderna          20255 non-null  object
 43  series_complete_pfizer           20255 non-null  object
 44  series_complete_unk_manuf        20255 non-null  object
 45  series_complete_janssen_12plus   20255 non-null  object
 46  series_complete_moderna_12plus   20255 non-null  object
 47  series_complete_pfizer_12plus    20255 non-null  object
 48  series_complete_unk_manuf_1      20255 non-null  object
 49  series_complete_janssen_18plus   20255 non-null  object
 50  series_complete_moderna_18plus   20255 non-null  object
 51  series_complete_pfizer_18plus    20255 non-null  object
 52  series_complete_unk_manuf_2      20255 non-null  object
 53  series_complete_janssen_65plus   20255 non-null  object
 54  series_complete_moderna_65plus   20255 non-null  object
 55  series_complete_pfizer_65plus    20255 non-null  object
 56  series_complete_unk_manuf_3      20255 non-null  object
 57  additional_doses                 4160 non-null   object
 58  additional_doses_vax_pct         19935 non-null  object
 59  additional_doses_18plus          19935 non-null  object
 60  additional_doses_18plus_vax_pct  19935 non-null  object
 61  additional_doses_50plus          19935 non-null  object
 62  additional_doses_50plus_vax_pct  20255 non-null  object
 63  additional_doses_65plus          19935 non-null  object
 64  additional_doses_65plus_vax_pct  19935 non-null  object
 65  additional_doses_moderna         19935 non-null  object
 66  additional_doses_pfizer          19935 non-null  object
 67  additional_doses_janssen         19935 non-null  object
 68  additional_doses_unk_manuf       19935 non-null  object
dtypes: object(69)
memory usage: 10.7+ MB

In [24]:
results_df = results_df[['date', 'location', 'distributed', 'administered', 'series_complete_yes', 'series_complete_pop_pct', 'additional_doses', 'additional_doses_vax_pct']]

In [12]:
results_df.head()

,date,location,distributed,administered,series_complete_yes,series_complete_pop_pct,additional_doses,additional_doses_vax_pct
0,2021-10-26T00:00:00.000,IA,4563315,3657561,1745363,55.3,160211,9.2
1,2021-10-26T00:00:00.000,US,504584715,415012026,190793100,57.5,13753793,7.2
2,2021-10-26T00:00:00.000,OH,16011445,12768269,6034821,51.6,480842,8
3,2021-10-26T00:00:00.000,AS,70650,65566,30902,55.5,22,0.1
4,2021-10-26T00:00:00.000,VI,115260,108001,48753,46.6,2370,4.9

In [25]:
results_df = results_df.rename(columns = {'location': 'state',
                                          'series_complete_yes': 'total vaccinated',
                                          'administered': 'total vaccines administered',
                                         'distributed': 'total vaccines distributed',
                                         'series_complete_pop_pct': 'pct vaccinated',
                                         'additional_doses': 'boosters administered'})

In [15]:
results_df.head()

,date,state,total vaccines distributed,total vaccines administered,total vaccinated,pct vaccinated,boosters administered,additional_doses_vax_pct
0,2021-10-26T00:00:00.000,IA,4563315,3657561,1745363,55.3,160211,9.2
1,2021-10-26T00:00:00.000,US,504584715,415012026,190793100,57.5,13753793,7.2
2,2021-10-26T00:00:00.000,OH,16011445,12768269,6034821,51.6,480842,8
3,2021-10-26T00:00:00.000,AS,70650,65566,30902,55.5,22,0.1
4,2021-10-26T00:00:00.000,VI,115260,108001,48753,46.6,2370,4.9

In [27]:
results_df['date'] = pd.to_datetime(results_df['date']).dt.date

In [29]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20255 entries, 0 to 20254
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         20255 non-null  object
 1   state                        20255 non-null  object
 2   total vaccines distributed   20255 non-null  object
 3   total vaccines administered  20255 non-null  object
 4   total vaccinated             20255 non-null  object
 5   pct vaccinated               20255 non-null  object
 6   boosters administered        4160 non-null   object
 7   additional_doses_vax_pct     19935 non-null  object
dtypes: object(8)
memory usage: 1.2+ MB

In [31]:
results_df['date']= pd.to_datetime(results_df['date'])

In [34]:
results_df = results_df.set_index('date')

In [37]:
results_df = results_df.loc['2021-10-25']

In [38]:
results_df

,state,total vaccines distributed,total vaccines administered,total vaccinated,pct vaccinated,boosters administered,additional_doses_vax_pct
date,,,,,,,
2021-10-25,ME,2302770,1919012,942546,70.1,68073,7.2
2021-10-25,MH,57140,42025,20218,34.6,9,0
2021-10-25,NV,4254060,3580718,1618862,52.6,100396,6.2
2021-10-25,SC,7398485,5614897,2553535,49.6,234471,9.2
2021-10-25,VI,115260,107633,48619,46.4,2218,4.6
...,...,...,...,...,...,...,...
2021-10-25,MI,14303410,11268319,5322469,53.3,499316,9.4
2021-10-25,VT,1128950,956952,442528,70.9,46323,10.5
2021-10-25,FL,34664565,28141859,12756457,59.4,1010007,7.9
2021-10-25,AK,1130765,856505,383032,52.4,42857,11.2
2021-10-25,RP,33090,31592,15680,87.6,564,3.6